### ISSUE TITLE
install error, environment is py 3.8.0

### ISSUE THREAD

**Issue by yang-arina** [NatureGeorge/pdb-profiling#29]
install command：pip install pdb-profiling==0.3.8 -i https://pypi.org/simple
error like this:
Collecting pdb-profiling==0.3.8
  Using cached pdb_profiling-0.3.8.tar.gz (336 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      Compiling pdb_profiling/cython/py_qcprot.pyx because it depends on /tmp/pip-build-env-vd8xsxub/overlay/lib/python3.8/site-packages/Cython/Includes/cpython/buffer.pxd.
      [1/1] Cythonizing pdb_profiling/cython/py_qcprot.pyx
      /tmp/pip-build-env-vd8xsxub/overlay/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-z78h8mky/pdb-profiling_976fe12e175a4847b685be23c5d76ed9/pdb_profiling/cython/py_qcprot.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      error in pdb_profiling setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.7.*'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by NatureGeorge** [comment]
Hi, thanks for trying `pdb-profiling`. This issue is due to the update of `setuptools`. You can now try `pip install pdb-profiling==0.3.9 -i https://pypi.org/simple`.

**NOTE: It is recommended to create a new conda environment to install `pdb-profiling`, since there are some highly constrained versions of dependent packages**.

**Comment by yang-arina** [comment]
Thank you very much for your response！ After using the new command line, I have now successfully completed the installation.
